# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productinorder_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='session_key',
        ),
    ]
