# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_productinorder_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товаров в корзине'},
        ),
    ]
